edit_uri: blob/master/docs/
markdown_extensions:
- admonition
- codehilite
- toc:
    permalink: true
nav:
- Home: index.md
- Introduction: pages/introduction.md
- Installation: pages/installation.md
- Getting Started: pages/getting_started.md
- API Documentation:
  - swarmrl.losses.proximal_policy_loss: pages/api/swarmrl.losses.proximal_policy_loss.md
  - swarmrl.losses.loss: pages/api/swarmrl.losses.loss.md
  - swarmrl.losses.policy_gradient_loss: pages/api/swarmrl.losses.policy_gradient_loss.md
  - swarmrl.tasks.task: pages/api/swarmrl.tasks.task.md
  - swarmrl.tasks.multi_tasking: pages/api/swarmrl.tasks.multi_tasking.md
  - swarmrl.tasks.searching.species_search: pages/api/swarmrl.tasks.searching.species_search.md
  - swarmrl.tasks.searching.gradient_sensing: pages/api/swarmrl.tasks.searching.gradient_sensing.md
  - swarmrl.tasks.object_movement.rod_rotation: pages/api/swarmrl.tasks.object_movement.rod_rotation.md
  - swarmrl.force_functions.force_fn: pages/api/swarmrl.force_functions.force_fn.md
  - swarmrl.sampling_strategies.categorical_distribution: pages/api/swarmrl.sampling_strategies.categorical_distribution.md
  - swarmrl.sampling_strategies.gumbel_distribution: pages/api/swarmrl.sampling_strategies.gumbel_distribution.md
  - swarmrl.sampling_strategies.sampling_strategy: pages/api/swarmrl.sampling_strategies.sampling_strategy.md
  - swarmrl.observables.concentration_field: pages/api/swarmrl.observables.concentration_field.md
  - swarmrl.observables.subdivided_vision_cones: pages/api/swarmrl.observables.subdivided_vision_cones.md
  - swarmrl.observables.observable: pages/api/swarmrl.observables.observable.md
  - swarmrl.observables.multi_sensing: pages/api/swarmrl.observables.multi_sensing.md
  - swarmrl.observables.position: pages/api/swarmrl.observables.position.md
  - swarmrl.observables.director: pages/api/swarmrl.observables.director.md
  - swarmrl.observables.particle_sensing: pages/api/swarmrl.observables.particle_sensing.md
  - swarmrl.agents.find_point: pages/api/swarmrl.agents.find_point.md
  - swarmrl.agents.actor_critic: pages/api/swarmrl.agents.actor_critic.md
  - swarmrl.agents.classical_agent: pages/api/swarmrl.agents.classical_agent.md
  - swarmrl.agents.dummy_models: pages/api/swarmrl.agents.dummy_models.md
  - swarmrl.agents.agent: pages/api/swarmrl.agents.agent.md
  - swarmrl.agents.bechinger_models: pages/api/swarmrl.agents.bechinger_models.md
  - swarmrl.utils.colloid_utils: pages/api/swarmrl.utils.colloid_utils.md
  - swarmrl.utils.utils: pages/api/swarmrl.utils.utils.md
  - swarmrl.exploration_policies.random_exploration: pages/api/swarmrl.exploration_policies.random_exploration.md
  - swarmrl.exploration_policies.exploration_policy: pages/api/swarmrl.exploration_policies.exploration_policy.md
  - swarmrl.trainers.continuous_trainer: pages/api/swarmrl.trainers.continuous_trainer.md
  - swarmrl.trainers.episodic_trainer: pages/api/swarmrl.trainers.episodic_trainer.md
  - swarmrl.trainers.trainer: pages/api/swarmrl.trainers.trainer.md
  - swarmrl.components.swarm: pages/api/swarmrl.components.swarm.md
  - swarmrl.components.colloid: pages/api/swarmrl.components.colloid.md
  - swarmrl.networks.flax_network: pages/api/swarmrl.networks.flax_network.md
  - swarmrl.networks.network: pages/api/swarmrl.networks.network.md
  - swarmrl.value_functions.expected_returns: pages/api/swarmrl.value_functions.expected_returns.md
  - swarmrl.value_functions.generalized_advantage_estimate: pages/api/swarmrl.value_functions.generalized_advantage_estimate.md
  - swarmrl.training_routines.ensemble_submit: pages/api/swarmrl.training_routines.ensemble_submit.md
  - swarmrl.training_routines.genetic_algorithm: pages/api/swarmrl.training_routines.genetic_algorithm.md
  - swarmrl.actions.actions: pages/api/swarmrl.actions.actions.md
  - swarmrl.engine.espresso: pages/api/swarmrl.engine.espresso.md
  - swarmrl.engine.real_experiment: pages/api/swarmrl.engine.real_experiment.md
  - swarmrl.engine.engine: pages/api/swarmrl.engine.engine.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - ../../SwarmRL
repo_name: SwarmRL/SwarmRL
repo_url: https://github.com/SwarmRL/SwarmRL
site_author: Your Name or Organization
site_description: A detailed documentation of the SwarmRL project
site_name: SwarmRL Documentation
site_url: https://example.com
theme:
  favicon: assets/images/favicon.ico
  features:
  - navigation.tabs
  - navigation.instant
  - navigation.top
  logo: assets/images/logo.jpg
  name: material
  palette:
    accent: indigo
    primary: indigo
