name: Build and Deploy Docusaurus Site with Sphinx API Docs

on:
    push:
    repository_dispatch:
        types: [update-docs]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout SwarmRL Website Repository
      uses: actions/checkout@v2
      with:
        path: 'SwarmRL-website'

    - name: Checkout SwarmRL Source Code
      uses: actions/checkout@v2
      with:
        repository: 'SwarmRL/SwarmRL'
        path: 'SwarmRL'

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # - name: Install Docusaurus Dependencies
    #   run: |
    #     cd SwarmRL-website
    #     npm install

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install Dependencies
      run: |
        cd SwarmRL-website
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Include any other dependencies your Sphinx docs might need

    - name: Generate API Documentation
      run: |
        cd SwarmRL
        pip install -e .
        cd ../
        cd SwarmRL-website
        cp mkdocs-template.yml mkdocs.yml
        python build-api-docs.py
        mkdocs gh-deploy

    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./SwarmRL-website/build
